services:
    akruijff.penalty_cards.controller:
        class: akruijff\penalty_cards\controller\board
        arguments:
            - '@controller.helper'

    akruijff.penalty_cards.listener:
        class: akruijff\penalty_cards\event\board_link
        arguments:
            - '@controller.helper'
        tags:
            - { name: event.listener }

    akruijff.penalty_cards.listener:
        class: akruijff\penalty_cards\event\main_listener
        arguments:
            - '@controller.helper'
        tags:
            - { name: event.listener }
