services:
    akruijff.penalty_cards.controller:
        class: akruijff\penalty_cards\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    akruijff.penalty_cards.listener:
        class: akruijff\penalty_cards\event\main_listener
        arguments:
            - '@auth'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
